# Generated by Django 3.2.16 on 2023-03-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_telegram_bot', '0002_alter_telegramuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='Пользователь авторизован?'),
        ),
    ]
