# Generated by Django 3.2.16 on 2023-03-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_telegram_bot', '0003_telegramuser_is_authorized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_authorized',
        ),
    ]
