# Generated by Django 3.2.16 on 2023-03-07 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest_telegram_bot', '0004_remove_telegramuser_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='contest_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь на Контесте'),
        ),
    ]
