# Generated by Django 3.2.18 on 2023-04-10 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest_telegram_bot', '0005_alter_telegramuser_contest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.BooleanField(default=True, verbose_name='Оповещения о комментариях')),
                ('announcements', models.BooleanField(default=True, verbose_name='Оповещения об объявлениях')),
                ('schedule', models.BooleanField(default=False, verbose_name='Оповещения о расписании')),
                ('deadlines', models.BooleanField(default=False, verbose_name='Оповещения о дедлайнах')),
                ('deadlines_interval', models.IntegerField(default=1, verbose_name='Интервал оповещения о дедлайнах')),
                ('submissions_creation', models.BooleanField(default=False, verbose_name='Оповещения об отправляемых посылках')),
                ('submissions_mark', models.BooleanField(default=True, verbose_name='Оповещения об оценке за посылки')),
                ('problems_mark', models.BooleanField(default=True, verbose_name='Оповещения об оценке за задачи')),
                ('courses_mark', models.BooleanField(default=True, verbose_name='Оповещения об оценке за курс')),
                ('questions', models.BooleanField(default=True, verbose_name='Оповещения о вопросах')),
                ('reports', models.BooleanField(default=True, verbose_name='Оповещения о сообщениях об ошибках')),
                ('assignments', models.BooleanField(default=True, verbose_name='Оповещения о назначениях задач')),
                ('contest_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь на Контесте')),
            ],
            options={
                'verbose_name': 'Пользователь в телеграме',
            },
        ),
    ]
