# Generated by Django 3.2.18 on 2023-04-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_telegram_bot', '0008_rename_schedule_telegramusersettings_schedules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramusersettings',
            old_name='problems_mark',
            new_name='assignments_mark',
        ),
    ]
