# Generated by Django 3.2.18 on 2023-04-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_telegram_bot', '0010_user_for_telegram_bot_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramusersettings',
            old_name='submissions_creation',
            new_name='submissions',
        ),
    ]
