# Generated by Django 3.2.18 on 2023-05-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_telegram_bot', '0011_rename_submissions_creation_telegramusersettings_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusersettings',
            name='deadlines',
        ),
        migrations.RemoveField(
            model_name='telegramusersettings',
            name='deadlines_interval',
        ),
    ]
