# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='since',
            field=models.PositiveSmallIntegerField(choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017),
        ),
    ]
