# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170325_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'отчислен'), (1, '1 курс, 1 семестр'), (2, '1 курс, 2 семестр'), (3, '2 курс, 1 семестр'), (4, '2 курс, 2 семестр'), (5, '3 курс, 1 семестр'), (6, '3 курс, 2 семестр'), (7, '4 курс, 1 семестр'), (8, '4 курс, 2 семестр'), (9, 'выпускник')], default=1),
        ),
    ]
