# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170406_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['user__last_name', 'user__first_name', 'user__id']},
        ),
    ]
