# Generated by Django 2.0 on 2017-12-29 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171228_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-latest_message__date_created',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='modification_date',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='timestamp',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
