# Generated by Django 2.2.5 on 2019-09-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190102_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='since',
            new_name='admission_year',
        ),
    ]
