# Generated by Django 2.2.5 on 2019-09-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190914_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='enrolled',
            field=models.BooleanField(default=True, verbose_name='Обучается?'),
        ),
        migrations.AddField(
            model_name='account',
            name='graduated',
            field=models.BooleanField(default=False, verbose_name='Закончил обучение?'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'студент'), (2, 'модератор'), (3, 'преподаватель')], default=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 курс, 1 семестр'), (2, '1 курс, 2 семестр'), (3, '2 курс, 1 семестр'), (4, '2 курс, 2 семестр'), (5, '3 курс, 1 семестр'), (6, '3 курс, 2 семестр'), (7, '4 курс, 1 семестр'), (8, '4 курс, 2 семестр')], default=1, verbose_name='Уровень'),
        ),
    ]
