# Generated by Django 2.2.5 on 2019-09-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190927_1953'),
    ]

    operations = []
