# Generated by Django 2.2.5 on 2019-10-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_arrange_account_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('user__last_name', 'user__first_name', 'user_id'), 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
    ]
