# Generated by Django 2.2.5 on 2020-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200111_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='old_id',
            field=models.PositiveIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='comment',
            name='old_id',
            field=models.PositiveIntegerField(default=None, null=True, unique=True),
        ),
    ]
