# Generated by Django 3.0.5 on 2020-05-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200501_1339'),
    ]

    operations = []
