# Generated by Django 3.0.5 on 2020-05-04 07:41
import json
import os
import sys

from django.conf import settings
from django.contrib.auth.models import User, Group
from django.db import migrations


ACCOUNTS_PATH = 'additional_tools/accounts.json'


def import_accounts(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')

    ids = {
        # actual id : old id
        52:    2,  # Павел Алисейчик
        53:  158,  # Юрий Шуткин
        109: 253,  # Станислав Чиревко
        203: 222,  # Сергей Родин
        206: 160,  # Дмитрий Алексеев
        209: 168,  # Кирилл Голиков
        312: 272,  # Наталья Дейнека
        314: 162,  # Александр Петюшко
        1:   275,  # Руслан Бекташев
    }
    for actual_id, old_id in ids.items():
        account = Account.objects.get(user_id=actual_id)
        account.old_id = old_id
        account.save()

    file_path = os.path.join(settings.BASE_DIR, ACCOUNTS_PATH)
    with open(file_path) as file:
        s = file.read()
    accounts = json.loads(s)
    new_accounts = list()
    group_student = Group.objects.get(name='Студент')
    groups = {}
    for account in accounts:
        user = User(
            username=account['username'],
            password=account['password'],
            first_name=account['first_name'],
            last_name=account['last_name'],
            email=account['email'],
            is_active=False
        )
        user.save()
        group_name = 'M' + str(account['admission_year'])[2:]
        if group_name not in groups:
            groups[group_name], _ = Group.objects.get_or_create(name=group_name)
        user.groups.add(group_student, groups[group_name])
        new_accounts.append(Account(
            user_id=user.pk,
            old_id=account['old_id'],
            enrolled=False,
            graduated=True,
            level=8,
            admission_year=account['admission_year']
        ))
    Account.objects.bulk_create(new_accounts)


def delete_users(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    file_path = os.path.join(settings.BASE_DIR, ACCOUNTS_PATH)
    with open(file_path) as file:
        s = file.read()
    accounts = json.loads(s)
    old_ids = list(map(lambda x: x['old_id'], accounts))
    users_ids = Account.objects.filter(old_id__in=old_ids).values_list('user_id')
    User.objects.filter(id__in=users_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200501_1339'),
    ]

    operations = [
        migrations.RunPython(import_accounts, delete_users, elidable=True),
    ] if 'test' not in sys.argv[1:] else []
