# Generated by Django 3.0.6 on 2020-05-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200501_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='old_id',
            field=models.PositiveIntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='old_id',
            field=models.PositiveIntegerField(default=None, null=True, unique=True),
        ),
    ]
