# Generated by Django 3.0.5 on 2020-05-04 07:41

from django.db import migrations
from django.contrib.auth.models import User
import json


def import_accounts(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    s = str()
    with open('additional_tools/accounts.json') as file:
        s = file.read()
    accounts = json.loads(s)
    new_accounts = list()
    for account in accounts:
        user = User.objects.create_user(
            username=account['username'],
            password=account['password'],
            first_name=account['first_name'],
            last_name=account['last_name'],
            email=account['email']
        )
        new_accounts.append(Account(
            user_id=user.id,
            old_id=account['old_id'],
            enrolled=account['enrolled'],
            graduated=account['graduated'],
            level=account['level'],
            admission_year=account['admission_year']
        ))
    Account.objects.bulk_create(new_accounts)


def delete_users(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    s = str()
    with open('additional_tools/accounts.json') as file:
        s = file.read()
    accounts = json.loads(s)
    for account in accounts:
        try:
            User.objects.get(id=Account.objects.get(old_id=account['old_id']).user.id).delete()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200504_1235'),
    ]

    operations = [
        migrations.RunPython(import_accounts, delete_users)
    ]
