# Generated by Django 3.0.5 on 2020-05-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_accounts_import'),
    ]

    operations = []
