# Generated by Django 2.2.12 on 2020-05-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_comments_import_1'),
    ]

    operations = []
