# Generated by Django 2.2.12 on 2020-05-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_comments_import_2'),
    ]

    operations = []
