# Generated by Django 2.2.12 on 2020-05-16 15:08
import sys

from django.db import migrations


def import_comments_last(apps, schema_editor):
    Comment = apps.get_model('accounts', 'Comment')

    comments = Comment.objects.filter(old_id__isnull=False)
    comments_thread_cache = {}
    comments_parent_cache = {}
    for comment in comments:
        if comment.thread_id not in comments_thread_cache:
            comments_thread_cache[comment.thread_id] = Comment.objects.get(old_id=comment.thread_id).id
        if comment.parent_id not in comments_parent_cache:
            comments_parent_cache[comment.parent_id] = Comment.objects.get(old_id=comment.parent_id).id
        comment.thread_id = comments_thread_cache[comment.thread_id]
        comment.parent_id = comments_parent_cache[comment.parent_id]
    Comment.objects.bulk_update(comments, ['thread_id', 'parent_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_comments_import_2'),
    ]

    operations = [
        migrations.RunPython(import_comments_last, migrations.RunPython.noop)
    ] if 'test' not in sys.argv[1:] else []
