# Generated by Django 2.2.13 on 2020-10-21 17:01

from django.db import migrations
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0031_comments_import_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscriptions',
            field=gm2m.fields.GM2MField('contests.Course', 'contests.Contest', 'contests.Problem', 'contests.Assignment', 'contests.Submission', on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribers', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
    ]
