# Generated by Django 2.2.13 on 2020-10-30 15:50

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0031_comments_import_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comments_read',
            field=models.ManyToManyField(to='accounts.Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscriptions',
            field=gm2m.fields.GM2MField(on_delete=django.db.models.deletion.DO_NOTHING, through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk')),
        ),
    ]
