# Generated by Django 2.2.13 on 2020-11-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20201103_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='old_id',
        ),
    ]
