# Generated by Django 2.2.13 on 2021-02-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20201205_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comments_read',
            field=models.ManyToManyField(blank=True, to='accounts.Comment'),
        ),
    ]
