# Generated by Django 2.2.13 on 2021-04-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20210427_0211'),
    ]

    operations = []
