# Generated by Django 2.2.13 on 2021-05-03 12:23

from django.db import migrations


def update_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')

    try:
        permission = Permission.objects.get(codename='add_answer')
        permission.delete()
        permission = Permission.objects.get(codename='change_answer')
        permission.delete()
        permission = Permission.objects.get(codename='check_answer')
        permission.delete()
        permission = Permission.objects.get(codename='delete_answer')
        permission.delete()
        permission = Permission.objects.get(codename='view_answer')
        permission.delete()

        permission = Permission.objects.get(codename='add_question', content_type_id=46)
        permission.delete()
        permission = Permission.objects.get(codename='change_question', content_type_id=46)
        permission.delete()
        permission = Permission.objects.get(codename='delete_question', content_type_id=46)
        permission.delete()
        permission = Permission.objects.get(codename='view_question', content_type_id=46)
        permission.delete()

        permission = Permission.objects.get(codename='add_test')
        permission.delete()
        permission = Permission.objects.get(codename='change_test')
        permission.delete()
        permission = Permission.objects.get(codename='delete_test')
        permission.delete()
        permission = Permission.objects.get(codename='view_test')
        permission.delete()

        permission = Permission.objects.get(codename='add_testmembership')
        permission.delete()
        permission = Permission.objects.get(codename='change_testmembership')
        permission.delete()
        permission = Permission.objects.get(codename='delete_testmembership')
        permission.delete()
        permission = Permission.objects.get(codename='view_testmembership')
        permission.delete()

        permission = Permission.objects.get(codename='add_testsubmission')
        permission.delete()
        permission = Permission.objects.get(codename='change_testsubmission')
        permission.delete()
        permission = Permission.objects.get(codename='delete_testsubmission')
        permission.delete()
        permission = Permission.objects.get(codename='view_testsubmission')
        permission.delete()

        permission = Permission.objects.get(codename='add_testsuite')
        permission.delete()
        permission = Permission.objects.get(codename='change_testsuite')
        permission.delete()
        permission = Permission.objects.get(codename='delete_testsuite')
        permission.delete()
        permission = Permission.objects.get(codename='view_testsuite')
        permission.delete()

        permission = Permission.objects.get(codename='add_testsuitesubmission')
        permission.delete()
        permission = Permission.objects.get(codename='change_testsuitesubmission')
        permission.delete()
        permission = Permission.objects.get(codename='delete_testsuitesubmission')
        permission.delete()
        permission = Permission.objects.get(codename='view_testsuitesubmission')
        permission.delete()
    except Permission.DoesNotExist:
        pass

    permission = Permission.objects.get(codename='add_faculty')
    permission.name = "Добавлять Факультет"
    permission.save()
    permission = Permission.objects.get(codename='change_faculty')
    permission.name = "Изменять Факультет"
    permission.save()
    permission = Permission.objects.get(codename='delete_faculty')
    permission.name = "Удалять Факультет"
    permission.save()
    permission = Permission.objects.get(codename='view_faculty')
    permission.name = "Просматривать Факультет"
    permission.save()

    permission = Permission.objects.get(codename='add_subscription')
    permission.name = "Добавлять Подписку"
    permission.save()
    permission = Permission.objects.get(codename='change_subscription')
    permission.name = "Изменять Подписку"
    permission.save()
    permission = Permission.objects.get(codename='delete_subscription')
    permission.name = "Удалять Подписку"
    permission.save()
    permission = Permission.objects.get(codename='view_subscription')
    permission.name = "Просматривать Подписку"
    permission.save()

    permission = Permission.objects.get(codename='add_filter')
    permission.name = "Добавлять Фильтр"
    permission.save()
    permission = Permission.objects.get(codename='change_filter')
    permission.name = "Изменять Фильтр"
    permission.save()
    permission = Permission.objects.get(codename='delete_filter')
    permission.name = "Удалять Фильтр"
    permission.save()
    permission = Permission.objects.get(codename='view_filter')
    permission.name = "Просматривать Фильтр"
    permission.save()

    permission = Permission.objects.get(codename='add_option')
    permission.name = "Добавлять Вариант ответа"
    permission.save()
    permission = Permission.objects.get(codename='change_option')
    permission.name = "Изменять Вариант ответа"
    permission.save()
    permission = Permission.objects.get(codename='delete_option')
    permission.name = "Удалять Вариант ответа"
    permission.save()
    permission = Permission.objects.get(codename='view_option')
    permission.name = "Просматривать Вариант ответа"
    permission.save()

    permission = Permission.objects.get(codename='add_submissionpattern')
    permission.name = "Добавлять Шаблон посылки"
    permission.save()
    permission = Permission.objects.get(codename='change_submissionpattern')
    permission.name = "Изменять Шаблон посылки"
    permission.save()
    permission = Permission.objects.get(codename='delete_submissionpattern')
    permission.name = "Удалять Шаблон посылки"
    permission.save()
    permission = Permission.objects.get(codename='view_submissionpattern')
    permission.name = "Просматривать Шаблон посылки"
    permission.save()

    permission = Permission.objects.get(codename='add_subproblem')
    permission.name = "Добавлять Подзадачу"
    permission.save()
    permission = Permission.objects.get(codename='change_subproblem')
    permission.name = "Изменять Подзадачу"
    permission.save()
    permission = Permission.objects.get(codename='delete_subproblem')
    permission.name = "Удалять Подзадачу"
    permission.save()
    permission = Permission.objects.get(codename='view_subproblem')
    permission.name = "Просматривать Подзадачу"
    permission.save()

    permission = Permission.objects.get(codename='add_schedule')
    permission.name = "Добавлять Расписание"
    permission.save()
    permission = Permission.objects.get(codename='change_schedule')
    permission.name = "Изменять Расписание"
    permission.save()
    permission = Permission.objects.get(codename='delete_schedule')
    permission.name = "Удалять Расписание"
    permission.save()
    permission = Permission.objects.get(codename='view_schedule')
    permission.name = "Просматривать Расписание"
    permission.save()

    permission = Permission.objects.get(codename='add_scheduleattachment')
    permission.name = "Добавлять Файл расписания"
    permission.save()
    permission = Permission.objects.get(codename='change_scheduleattachment')
    permission.name = "Изменять Файл расписания"
    permission.save()
    permission = Permission.objects.get(codename='delete_scheduleattachment')
    permission.name = "Удалять Файл расписания"
    permission.save()
    permission = Permission.objects.get(codename='view_scheduleattachment')
    permission.name = "Просматривать Файл расписания"
    permission.save()

    permission = Permission.objects.get(codename='add_report')
    permission.name = "Добавлять Сообщение об ошибке"
    permission.save()
    permission = Permission.objects.get(codename='change_report')
    permission.name = "Изменять Сообщение об ошибке"
    permission.save()
    permission = Permission.objects.get(codename='delete_report')
    permission.name = "Удалять Сообщение об ошибке"
    permission.save()
    permission = Permission.objects.get(codename='view_report')
    permission.name = "Просматривать Сообщение об ошибке"
    permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210427_0211'),
    ]

    operations = [
        migrations.RunPython(update_permissions, migrations.RunPython.noop)
    ]
