# Generated by Django 2.2.13 on 2021-05-03 12:23
import sys

from django.contrib.auth.management import create_permissions
from django.db import migrations


def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None


def delete_permissions(model, codenames):
    for codename in codenames:
        permission = model.objects.get(codename=codename)
        permission.delete()


def rename_permissions(model, name_pairs):
    for codename, name in name_pairs:
        permission = model.objects.get(codename=codename)
        permission.name = name
        permission.save()


def update_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')

    try:
        delete_permissions(Permission, [
            'add_answer',
            'change_answer',
            'check_answer',
            'delete_answer',
            'view_answer',
        ])

        for codename in ['add_question', 'change_question', 'delete_question', 'view_question']:
            permission = Permission.objects.get(codename=codename, content_type_id=46)
            permission.delete()

        delete_permissions(Permission, [
            'add_test',
            'change_test',
            'delete_test',
            'view_test',
        ])

        delete_permissions(Permission, [
            'add_testmembership',
            'change_testmembership',
            'delete_testmembership',
            'view_testmembership',
        ])

        delete_permissions(Permission, [
            'add_testsubmission',
            'change_testsubmission',
            'delete_testsubmission',
            'view_testsubmission',
        ])

        delete_permissions(Permission, [
            'add_testsuite',
            'change_testsuite',
            'delete_testsuite',
            'view_testsuite',
        ])

        delete_permissions(Permission, [
            'add_testsuitesubmission',
            'change_testsuitesubmission',
            'delete_testsuitesubmission',
            'view_testsuitesubmission',
        ])
    except Permission.DoesNotExist:
        pass

    rename_permissions(Permission, [
        ('add_faculty', "Добавлять Факультет"),
        ('change_faculty', "Изменять Факультет"),
        ('delete_faculty', "Удалять Факультет"),
        ('view_faculty', "Просматривать Факультет"),
    ])

    rename_permissions(Permission, [
        ('add_subscription', "Добавлять Подписку"),
        ('change_subscription', "Изменять Подписку"),
        ('delete_subscription', "Удалять Подписку"),
        ('view_subscription', "Просматривать Подписку"),
    ])

    rename_permissions(Permission, [
        ('add_filter', "Добавлять Фильтр"),
        ('change_filter', "Изменять Фильтр"),
        ('delete_filter', "Удалять Фильтр"),
        ('view_filter', "Просматривать Фильтр"),
    ])

    rename_permissions(Permission, [
        ('add_option', "Добавлять Вариант ответа"),
        ('change_option', "Изменять Вариант ответа"),
        ('delete_option', "Удалять Вариант ответа"),
        ('view_option', "Просматривать Вариант ответа"),
    ])

    rename_permissions(Permission, [
        ('add_submissionpattern', "Добавлять Шаблон посылки"),
        ('change_submissionpattern', "Изменять Шаблон посылки"),
        ('delete_submissionpattern', "Удалять Шаблон посылки"),
        ('view_submissionpattern', "Просматривать Шаблон посылки"),
    ])

    rename_permissions(Permission, [
        ('add_subproblem', "Добавлять Подзадачу"),
        ('change_subproblem', "Изменять Подзадачу"),
        ('delete_subproblem', "Удалять Подзадачу"),
        ('view_subproblem', "Просматривать Подзадачу"),
    ])

    rename_permissions(Permission, [
        ('add_schedule', "Добавлять Расписание"),
        ('change_schedule', "Изменять Расписание"),
        ('delete_schedule', "Удалять Расписание"),
        ('view_schedule', "Просматривать Расписание"),
    ])

    rename_permissions(Permission, [
        ('add_scheduleattachment', "Добавлять Файл расписания"),
        ('change_scheduleattachment', "Изменять Файл расписания"),
        ('delete_scheduleattachment', "Удалять Файл расписания"),
        ('view_scheduleattachment', "Просматривать Файл расписания"),
    ])

    rename_permissions(Permission, [
        ('add_report', "Добавлять Сообщение об ошибке"),
        ('change_report', "Изменять Сообщение об ошибке"),
        ('delete_report', "Удалять Сообщение об ошибке"),
        ('view_report', "Просматривать Сообщение об ошибке"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210427_0211'),
    ]

    operations = [
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop),
        migrations.RunPython(update_permissions, migrations.RunPython.noop)
    ] if 'test' not in sys.argv[1:] else []
