# Generated by Django 2.2.13 on 2021-05-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210427_0211'),
    ]

    operations = []
