# Generated by Django 2.2.13 on 2021-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20210503_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='group_name',
            field=models.CharField(default='Математики', max_length=50, verbose_name='Наименование группы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='group_prefix',
            field=models.CharField(default='М', max_length=5, verbose_name='Префикс группы'),
            preserve_default=False,
        ),
    ]
