# Generated by Django 2.2.13 on 2021-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20210503_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Баллы'),
        ),
    ]
