# Generated by Django 2.2.13 on 2021-06-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_account_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='score',
        ),
    ]
