# Generated by Django 2.2.13 on 2021-07-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_remove_account_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='record_book_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='№ зачетной книжки'),
        ),
    ]
