# Generated by Django 2.2.13 on 2021-07-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_account_record_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='short_name',
            field=models.CharField(default='', max_length=50, verbose_name='Краткое наименование'),
            preserve_default=False,
        ),
    ]
