# Generated by Django 2.2.13 on 2021-07-14 12:45

from django.db import migrations


def update_faculty(model, name, short_name):
    faculty = model.objects.get(name=name)
    faculty.short_name = short_name
    faculty.save()


def update_faculties(apps, schema_editor):
    Faculty = apps.get_model('accounts', 'Faculty')
    new_data = [
        ("Прикладная Математика и Информатика", "ПМиИ"),
        ("Психология", "Психология"),
        ("Филология", "Филология"),
        ("Реклама и Связи с Общественностью", "РиСО"),
    ]
    for data in new_data:
        update_faculty(Faculty, data[0], data[1])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_faculty_short_name'),
    ]

    operations = [
        migrations.RunPython(update_faculties, migrations.RunPython.noop)
    ]
