# Generated by Django 2.2.13 on 2021-07-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_faculty_short_name'),
    ]

    operations = []
