# Generated by Django 2.2.13 on 2021-07-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210714_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='Группа'),
        ),
    ]
