# Generated by Django 2.2.24 on 2021-11-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_notification_relation'),
    ]

    operations = []
