# Generated by Django 2.2.25 on 2022-02-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20211127_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='admission_year',
            field=models.PositiveSmallIntegerField(choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Год поступления'),
        ),
    ]
