# Generated by Django 2.2.25 on 2022-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20220203_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subgroup',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Подгруппа'),
        ),
    ]
