# Generated by Django 2.2.25 on 2022-02-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20220212_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
