# Generated by Django 2.2.25 on 2022-02-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_delete_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chat',
            name='latest_message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_a',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_b',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
