# Generated by Django 2.2.25 on 2022-02-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_auto_20220215_1814'),
    ]

    operations = []
