# Generated by Django 2.2.25 on 2022-03-04 15:45

from django.db import migrations


def update_contenttypes(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    contenttype_params = [
        ('accounts', 'activity'), ('accounts', 'chat'), ('accounts', 'message'), ('accounts', 'subscription'),
        ('contests', 'answer'), ('contests', 'event'), ('contests', 'lecture'), ('contests', 'question'),
        ('contests', 'tag'), ('contests', 'test'), ('contests', 'testmembership'), ('contests', 'testsuite'),
        ('contests', 'testsuitesubmission'),
    ]
    for app_label, model in contenttype_params:
        ContentType.objects.filter(app_label=app_label, model=model).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20220225_2037'),
    ]

    operations = [
        migrations.RunPython(update_contenttypes, migrations.RunPython.noop, elidable=True)
    ]
