# Generated by Django 2.2.25 on 2022-03-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_auto_20220225_2037'),
    ]

    operations = []
