# Generated by Django 2.2.25 on 2022-03-04 18:22

from django.db import migrations


def update_permissions(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    instructor_group = Group.objects.get_or_create(name="Преподаватель")
    permission_codenames = [
        'add_announcement', 'change_announcement', 'delete_announcement',
        'change_comment', 'delete_comment',
        'add_assignment', 'change_assignment', 'delete_assignment', 'view_assignment', 'view_assignment_table',
        'add_attachment', 'change_attachment', 'delete_attachment', 'view_attachment',
        'add_contest', 'change_contest', 'delete_contest', 'view_contest',
        'change_course', 'delete_course', 'view_course',
        'add_credit', 'change_credit', 'delete_credit', 'view_credit',
        'add_iotest', 'change_iotest', 'delete_iotest', 'view_iotest',
        'add_uttest', 'change_uttest', 'delete_uttest', 'view_uttest',
        'add_fntest', 'change_fntest', 'delete_fntest', 'view_fntest',
        'add_option', 'change_option', 'delete_option', 'view_option',
        'add_problem', 'change_problem', 'delete_problem', 'view_problem',
        'add_submission', 'change_submission', 'view_submission', 'download_submission', 'evaluate_submission', 'moss_submission', 'view_submission_list',
        'add_submissionpattern', 'change_submissionpattern', 'delete_submissionpattern', 'view_submissionpattern',
        'add_subproblem', 'change_subproblem', 'delete_subproblem', 'view_subproblem',
        'add_schedule', 'change_schedule', 'delete_schedule',
        'add_scheduleattachment', 'change_scheduleattachment', 'delete_scheduleattachment', 'view_scheduleattachment',
        'add_question', 'change_question'
    ]
    permissions = Permission.objects.filter(codename__in=permission_codenames)
    instructor_group.permissions.remove(*permissions)

    student_group = Group.objects.get_or_create(name="Студент")
    permission_codenames = [
        'view_course', 'view_contest', 'view_problem'
    ]
    permissions = Permission.objects.filter(codename__in=permission_codenames)
    student_group.permissions.remove(*permissions)

    moderator_group = Group.objects.get_or_create(name="Модератор")
    permission_codenames = [
        'view_discussion', 'add_filter', 'delete_filter', 'add_faculty'
    ]
    permissions = Permission.objects.filter(codename__in=permission_codenames)
    moderator_group.permissions.add(*permissions)

    for user_id in (720, 721, 724):
        try:
            user = User.objects.get(id=user_id)
            user.user_permissions.clear()
        except User.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20220304_1845'),
    ]

    operations = [
        migrations.RunPython(update_permissions, migrations.RunPython.noop)
    ]
