# Generated by Django 2.2.25 on 2022-03-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_auto_20220304_1845'),
    ]

    operations = []
