# Generated by Django 2.2.28 on 2022-05-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_auto_20220304_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='actual',
            field=models.DateField(blank=True, null=True, verbose_name='Актуально до'),
        ),
    ]
