# Generated by Django 3.2.16 on 2023-03-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='admission_year',
            field=models.PositiveSmallIntegerField(choices=[(2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023, verbose_name='Год поступления'),
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 курс, I семестр'), (2, '1 курс, II семестр'), (3, '2 курс, III семестр'), (4, '2 курс, IV семестр'), (5, '3 курс, V семестр'), (6, '3 курс, VI семестр'), (7, '4 курс, VII семестр'), (8, '4 курс, VIII семестр'), (9, '1 курс, I семестр, магистратура'), (10, '1 курс, II семестр, магистратура'), (11, '2 курс, III семестр, магистратура'), (12, '2 курс, IV семестр, магистратура')], default=1, verbose_name='Уровень'),
        ),
    ]
