# Generated by Django 3.2.18 on 2023-04-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_alter_account_admission_year'),
        ('accounts', '0066_auto_20230306_0107'),
    ]

    operations = [
    ]
