# Generated by Django 3.2.18 on 2023-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_merge_20230411_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'студент'), (2, 'модератор'), (3, 'преподаватель'), (4, 'автор курса')], default=1, verbose_name='Тип'),
        ),
    ]
