# Generated by Django 3.2.19 on 2023-05-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('user__last_name', 'user__first_name', 'user_id'), 'permissions': [('view_deleted', 'Просматривать корзину')], 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
    ]
