# Generated by Django 3.2.19 on 2023-06-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_account_options'),
    ]

    operations = []
