# Generated by Django 3.2.19 on 2023-06-02 14:14
from django.db import migrations


def update_moderator_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.get(name='Модератор')
    permission = Permission.objects.get(codename='view_deleted')
    group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_account_options'),
    ]

    operations = [
        migrations.RunPython(update_moderator_permissions, migrations.RunPython.noop, elidable=True)
    ]
