# Generated by Django 3.2.19 on 2023-06-02 14:14
from django.contrib.auth.management import create_permissions
from django.db import migrations


def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None


def update_moderator_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.get(name='Модератор')
    permission = Permission.objects.get(codename='view_deleted')
    group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_account_options'),
    ]

    operations = [
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop, elidable=True),
        migrations.RunPython(update_moderator_permissions, migrations.RunPython.noop, elidable=True)
    ]
