# Generated by Django 3.2.19 on 2023-12-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_auto_20230602_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'студент'), (2, 'модератор'), (3, 'преподаватель'), (4, 'автор курса')], default=1, verbose_name='Тип'),
        ),
    ]
