# Generated by Django 3.2.23 on 2024-04-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_auto_20230602_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='admission_year',
            field=models.PositiveSmallIntegerField(verbose_name='Год поступления'),
        ),
    ]
