# Generated by Django 4.2 on 2023-05-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportForCourse',
        ),
    ]
