# Generated by Django 4.2 on 2023-05-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_reportforcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportforcourse',
            options={'ordering': ('-date_created',), 'verbose_name': 'Сообщение об ошибке course', 'verbose_name_plural': 'Сообщения об ошибках course'},
        ),
    ]
