# Generated by Django 4.2 on 2023-05-13 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0143_auto_20230408_1349'),
        ('support', '0004_alter_reportforcourse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportforcourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.course'),
            preserve_default=False,
        ),
    ]
