# Generated by Django 4.2 on 2023-05-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_reportforcourse_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportforcourse',
            name='course',
        ),
    ]
