# Generated by Django 4.2 on 2023-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_remove_reportforcourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportforcourse',
            name='page_url',
            field=models.URLField(default=1, verbose_name='Откуда отправлено'),
            preserve_default=False,
        ),
    ]
