# Generated by Django 2.2.5 on 2019-12-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20191228_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
