# Generated by Django 2.2.5 on 2019-12-28 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0007_auto_20191228_0538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='Question',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-date_created',), 'verbose_name': 'Багрепорт', 'verbose_name_plural': 'Багрепорты'},
        ),
    ]
