# Generated by Django 2.2.13 on 2021-04-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20210323_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-date_created',), 'verbose_name': 'Сообщение об ошибке', 'verbose_name_plural': 'Сообщения об ошибках'},
        ),
        migrations.AddField(
            model_name='report',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
    ]
