# Generated by Django 2.2.13 on 2021-04-22 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0011_auto_20210403_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='addressee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Адресат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='redirect_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к переадресации'),
        ),
    ]
