# Generated by Django 2.2.13 on 2021-04-24 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_auto_20210423_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='addressee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Адресат'),
        ),
    ]
