# Generated by Django 2.2.24 on 2021-09-13 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0014_auto_20210424_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialStepPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=100, verbose_name='Вью')),
                ('step', models.CharField(max_length=100, verbose_name='Шаг')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Шаг руководства',
                'verbose_name_plural': 'Шаги руководства',
            },
        ),
    ]
