# Generated by Django 2.2.24 on 2021-10-13 22:38
import sys

from django.db import migrations


def create_discussion(apps, schema_editor):
    Discussion = apps.get_model('support', 'Discussion')
    Discussion.objects.get_or_create(owner_id=1, topic="Чат с разработчиками")


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_discussion'),
    ]

    operations = [
        migrations.RunPython(create_discussion, migrations.RunPython.noop, elidable=True)
    ] if 'test' not in sys.argv[1:] else []
