# Generated by Django 2.2.24 on 2021-10-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_discussion'),
    ]

    operations = []
