# Generated by Django 2.2.24 on 2021-10-14 15:57
import sys

from django.contrib.auth.management import create_permissions
from django.db import migrations


def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None


def rename_permissions(model, name_pairs):
    for codename, name in name_pairs:
        permission = model.objects.get(codename=codename)
        permission.name = name
        permission.save()


def update_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    rename_permissions(Permission, [
        ('add_discussion', "Добавлять Обсуждение"),
        ('change_discussion', "Изменять Обсуждение"),
        ('delete_discussion', "Удалять Обсуждение"),
        ('view_discussion', "Просматривать Обсуждение"),
    ])
    rename_permissions(Permission, [
        ('add_courseleader', "Добавлять Преподавателя курса"),
        ('change_courseleader', "Изменять Преподавателя курса"),
        ('delete_courseleader', "Удалять Преподавателя курса"),
        ('view_courseleader', "Просматривать Преподавателя курса"),
    ])
    rename_permissions(Permission, [
        ('add_tutorialsteppass', "Добавлять Шаг руководства"),
        ('change_tutorialsteppass', "Изменять Шаг руководства"),
        ('delete_tutorialsteppass', "Удалять Шаг руководства"),
        ('view_tutorialsteppass', "Просматривать Шаг руководства"),
    ])
    group = Group.objects.get(name='Преподаватель')
    permission = Permission.objects.get(codename='view_discussion')
    group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20211014_1548'),
    ]

    operations = [
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop),
        migrations.RunPython(update_permissions, migrations.RunPython.noop)
    ] if 'test' not in sys.argv[1:] else []
