# Generated by Django 2.2.24 on 2021-10-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_auto_20211014_1548'),
    ]

    operations = []
