# Generated by Django 2.2.25 on 2022-04-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_auto_20211014_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Опубликованный ответ виден всем пользователям', verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='question',
            name='redirect_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий адресату'),
        ),
    ]
