# Generated by Django 2.2.12 on 2020-10-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date_from', models.DateField(default=schedule.models.current_week_date_from, verbose_name='Начало интервала')),
                ('date_to', models.DateField(default=schedule.models.current_week_date_to, verbose_name='Конец интервала')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ('-date_from', '-date_to', '-date_created'),
                'abstract': False,
                'unique_together': {('date_from', 'date_to')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to=schedule.models.schedule_attachment_file_path, verbose_name='Файл')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule', verbose_name='Расписание')),
            ],
            options={
                'ordering': ('date_created',),
                'abstract': False,
            },
        ),
    ]
