# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'Задача решена'), ('WA', 'Неверный ответ'), ('NA', 'Ответ отсутствует'), ('CE', 'Ошибка компиляции'), ('RE', 'Ошибка выполнения'), ('FE', 'Ошибка операций с плавающей точкой'), ('SF', 'Ошибка при работе с памятью'), ('TL', 'Превышено ограничение по времени'), ('ML', 'Превышен ограничение по памяти')], max_length=2, verbose_name='Статус')),
                ('time_used', models.FloatField(null=True, verbose_name='Затрачено времени')),
                ('memory_used', models.PositiveIntegerField(null=True, verbose_name='Затрачено памяти')),
                ('compiler_output', models.TextField(null=True, verbose_name='Вывод компилятора')),
                ('program_output', models.TextField(null=True, verbose_name='Вывод программы')),
                ('answer_difference', models.TextField(null=True, verbose_name='Разность ответов')),
                ('total_score', models.PositiveIntegerField(null=True, verbose_name='Счет')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Вердикты',
                'verbose_name': 'Вердикт',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='iotest',
            options={'ordering': ['creation_date'], 'verbose_name': 'i/o-тест задачи', 'verbose_name_plural': 'i/o-тесты задачи'},
        ),
        migrations.RenameField(
            model_name='lessonattachment',
            old_name='source',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='submissionattachment',
            old_name='source',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='iotest',
            name='number',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='compilation_log',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='elapsed_time',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='evaluation_log',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='failed_test',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='memory_usage',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='passed_tests',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='iotest',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='iotest',
            name='title',
            field=models.CharField(default='i/o-тест', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Легко'), (1, 'Средне'), (2, 'Тяжело'), (3, 'Вызов')], default=0, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='failed_iotest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.IOTest', verbose_name='Проваленный тест'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.Submission', verbose_name='Посылка'),
        ),
    ]
