# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20161011_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='modification_date',
        ),
        migrations.AlterField(
            model_name='verdict',
            name='failed_iotest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.IOTest', verbose_name='Проваленный тест'),
        ),
    ]
