# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20161012_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_accomplished',
        ),
        migrations.AlterField(
            model_name='iotest',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
