# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20161225_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotest',
            name='input',
            field=models.TextField(blank=True, verbose_name='Входные данные'),
        ),
        migrations.AlterField(
            model_name='iotest',
            name='output',
            field=models.TextField(blank=True, verbose_name='Выходные данные'),
        ),
    ]
