# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20170323_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 курс, 1 семестр'), (2, '1 курс, 2 семестр'), (3, '2 курс, 1 семестр'), (4, '2 курс, 2 семестр'), (5, '3 курс, 1 семестр'), (6, '3 курс, 2 семестр'), (7, '4 курс, 1 семестр'), (8, '4 курс, 2 семестр')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
