# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:43
from __future__ import unicode_literals

import contests.misc
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20170323_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='iotest',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='lessonattachment',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='submissionattachment',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterModelOptions(
            name='verdict',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='latest_submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Submission'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Problem'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_limit',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Course'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Course'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='mark',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iotest',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='iotest',
            name='input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='iotest',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='iotest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iotest',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Problem'),
        ),
        migrations.AlterField(
            model_name='iotest',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='file',
            field=models.FileField(upload_to=contests.misc.lesson_attachment_path),
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Lesson'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Легко'), (1, 'Средне'), (2, 'Тяжело'), (3, 'Вызов')], default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.PositiveIntegerField(default=65536),
        ),
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Problem'),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='file',
            field=models.FileField(upload_to=contests.misc.submission_attachment_path),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Submission'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='answer_difference',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='compiler_output',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='failed_iotest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.IOTest'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='memory_used',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='program_output',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='status',
            field=models.CharField(choices=[('OK', 'Задача решена'), ('WA', 'Неверный ответ'), ('NA', 'Ответ отсутствует'), ('CE', 'Ошибка компиляции'), ('RE', 'Ошибка выполнения'), ('FE', 'Ошибка операций с плавающей точкой'), ('SF', 'Ошибка при работе с памятью'), ('TL', 'Превышено ограничение по времени'), ('ML', 'Превышен ограничение по памяти')], max_length=2),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.Submission'),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='time_used',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='verdict',
            name='total_score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
