# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20170323_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verdict',
            old_name='time_used',
            new_name='time_spent',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='verdict',
            name='status',
            field=models.CharField(choices=[('OK', 'Задача решена'), ('WA', 'Неверный ответ'), ('NA', 'Ответ отсутствует'), ('CE', 'Ошибка компиляции'), ('RE', 'Ошибка выполнения'), ('FE', 'Ошибка операций с плавающей точкой'), ('SF', 'Ошибка при работе с памятью'), ('TL', 'Превышено ограничение по времени'), ('ML', 'Превышено ограничение по памяти')], max_length=2),
        ),
    ]
