# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20170324_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 25, 12, 15, 53, 511032, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
