# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_credit_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='mark',
            new_name='score',
        ),
    ]
