# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0013_unittest'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unittest',
            name='arguments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='verdict',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='verdict',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
