# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:55
from __future__ import unicode_literals

import contests.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('contests', '0014_auto_20170402_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=contests.models.attachment_path)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['creation_date'],
            },
        ),
        migrations.RemoveField(
            model_name='lessonattachment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='submissionattachment',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='failed_iotest',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='submission',
        ),
        migrations.AlterModelOptions(
            name='iotest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unittest',
            options={},
        ),
        migrations.RenameField(
            model_name='unittest',
            old_name='arguments',
            new_name='command',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='latest_submission',
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('EX', 'Отлично'), ('GO', 'Хорошо'), ('SA', 'Удовлетворительно'), ('PO', 'Неудовлетворительно'), ('UN', 'Неизвестно')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='submission',
            name='answer_difference',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='compiler_output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_test_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='failed_test_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_used',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='program_output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('OK', 'Задача решена'), ('WA', 'Неверный ответ'), ('NA', 'Ответ отсутствует'), ('CE', 'Ошибка компиляции'), ('RE', 'Ошибка выполнения'), ('FE', 'Ошибка операций с плавающей точкой'), ('SF', 'Ошибка при работе с памятью'), ('TL', 'Превышено ограничение по времени'), ('ML', 'Превышено ограничение по памяти'), ('UN', 'Задача не проверена')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_spent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LessonAttachment',
        ),
        migrations.DeleteModel(
            name='SubmissionAttachment',
        ),
        migrations.DeleteModel(
            name='Verdict',
        ),
    ]
