# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_auto_20170404_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotest',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='unittest',
            name='difficulty',
        ),
    ]
