# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0017_auto_20170406_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitTest',
            new_name='UTTest',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('OK', 'Задача решена'), ('WA', 'Неверный ответ'), ('TF', 'Тест провален'), ('NA', 'Ответ отсутствует'), ('CE', 'Ошибка компиляции'), ('RE', 'Ошибка выполнения'), ('FE', 'Ошибка операций с плавающей точкой'), ('SF', 'Ошибка при работе с памятью'), ('TL', 'Превышено ограничение по времени'), ('ML', 'Превышено ограничение по памяти'), ('UN', 'Задача не проверена')], default='UN', max_length=2),
        ),
    ]
