# Generated by Django 2.0 on 2017-12-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0019_auto_20170513_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='iotest',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='uttest',
            options={'ordering': ('date_created',)},
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='modification_date',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='modification_date',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='modification_date',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='modification_date',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='iotest',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='iotest',
            old_name='modification_date',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='modification_date',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='modification_date',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='uttest',
            old_name='creation_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='uttest',
            old_name='modification_date',
            new_name='date_updated',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='modification_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='modification_date',
        ),
    ]
