# Generated by Django 2.0 on 2017-12-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0020_auto_20171229_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ('date_created',)},
        ),
        migrations.RemoveField(
            model_name='credit',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='uttest',
            name='args',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
