# Generated by Django 2.0 on 2017-12-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0021_auto_20171229_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('date_created',), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('date_created',), 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ('date_created',), 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('date_created',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ('date_created',), 'verbose_name': 'Зачет', 'verbose_name_plural': 'Зачеты'},
        ),
        migrations.AlterModelOptions(
            name='iotest',
            options={'ordering': ('date_created',), 'verbose_name': 'IO-тест', 'verbose_name_plural': 'IO-тесты'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('date_created',), 'verbose_name': 'Лекция', 'verbose_name_plural': 'Лекции'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('date_created',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-date_created',), 'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
        migrations.AlterModelOptions(
            name='uttest',
            options={'ordering': ('date_created',), 'verbose_name': 'UT-тест', 'verbose_name_plural': 'UT-тесты'},
        ),
        migrations.AlterField(
            model_name='credit',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(5, 'отлично'), (4, 'хорошо'), (3, 'удовлетворительно'), (2, 'неудовлетворительно'), (0, 'нет оценки')], default=0),
        ),
    ]
