# Generated by Django 2.0.1 on 2018-01-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0025_auto_20180111_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='contests.Tag'),
        ),
    ]
