# Generated by Django 2.0.1 on 2018-01-11 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0026_auto_20180111_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Лекция'), (2, 'Семинар'), (3, 'Коллоквиум'), (4, 'Зачет'), (5, 'Экзамен'), (6, 'Пересдача'), (7, 'Семестр')], default=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
