# Generated by Django 2.0.1 on 2018-01-13 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('contests', '0027_auto_20180111_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('test_id', models.PositiveIntegerField()),
                ('passed', models.BooleanField()),
                ('compilation_time', models.FloatField(blank=True)),
                ('compilation_stdout', models.TextField(blank=True)),
                ('compilation_stderr', models.TextField(blank=True)),
                ('execution_memory', models.PositiveIntegerField(blank=True)),
                ('execution_time', models.FloatField(blank=True)),
                ('execution_stdout', models.TextField(blank=True)),
                ('execution_stderr', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запуск',
                'verbose_name_plural': 'Запуски',
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='status',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='answer_difference',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='compiler_output',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='failed_test_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='failed_test_type',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='memory_used',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='program_output',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C')], default='C++', max_length=8),
        ),
        migrations.AddField(
            model_name='execution',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Submission'),
        ),
        migrations.AddField(
            model_name='execution',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
