# Generated by Django 2.0.1 on 2018-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0028_auto_20180114_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
