# Generated by Django 2.0.1 on 2018-01-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0029_auto_20180115_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
