# Generated by Django 2.0.1 on 2018-02-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0031_auto_20180123_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uttest',
            old_name='args',
            new_name='launch_args',
        ),
        migrations.AddField(
            model_name='iotest',
            name='compile_args',
            field=models.CharField(blank=True, max_length=255, verbose_name='Параметры компиляции'),
        ),
        migrations.AddField(
            model_name='iotest',
            name='compile_args_override',
            field=models.BooleanField(default=False, verbose_name='Заменить параметры компиляции из задачи?'),
        ),
        migrations.AddField(
            model_name='iotest',
            name='launch_args',
            field=models.CharField(blank=True, max_length=255, verbose_name='Параметры запуска'),
        ),
        migrations.AddField(
            model_name='iotest',
            name='launch_args_override',
            field=models.BooleanField(default=False, verbose_name='Заменить параметры запуска из задачи?'),
        ),
        migrations.AddField(
            model_name='problem',
            name='compile_args',
            field=models.CharField(blank=True, max_length=255, verbose_name='Параметры компиляции'),
        ),
        migrations.AddField(
            model_name='problem',
            name='launch_args',
            field=models.CharField(blank=True, max_length=255, verbose_name='Параметры запуска'),
        ),
        migrations.AddField(
            model_name='uttest',
            name='compile_args',
            field=models.CharField(blank=True, max_length=255, verbose_name='Параметры компиляции'),
        ),
        migrations.AddField(
            model_name='uttest',
            name='compile_args_override',
            field=models.BooleanField(default=False, verbose_name='Заменить параметры компиляции из задачи?'),
        ),
        migrations.AddField(
            model_name='uttest',
            name='launch_args_override',
            field=models.BooleanField(default=False, verbose_name='Заменить параметры запуска из задачи?'),
        ),
    ]
