# Generated by Django 2.0.2 on 2018-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0032_auto_20180202_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='remark',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пометка'),
        ),
    ]
