# Generated by Django 2.1.2 on 2018-11-19 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0034_problem_is_testable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FNTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('compile_args', models.CharField(blank=True, max_length=255, verbose_name='Параметры компиляции')),
                ('compile_args_override', models.BooleanField(default=False, verbose_name='Заменить параметры компиляции из задачи?')),
                ('launch_args', models.CharField(blank=True, max_length=255, verbose_name='Параметры запуска')),
                ('launch_args_override', models.BooleanField(default=False, verbose_name='Заменить параметры запуска из задачи?')),
                ('handler', models.CharField(max_length=100, verbose_name='Обработчик')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'FN-тест',
                'verbose_name_plural': 'FN-тесты',
                'ordering': ('date_created',),
                'abstract': False,
            },
        ),
    ]
