# Generated by Django 2.1.2 on 2018-11-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0035_fntest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='output',
            new_name='test_output',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='passed',
        ),
        migrations.AddField(
            model_name='execution',
            name='execution_summary',
            field=models.TextField(blank=True, verbose_name='Сводка запуска'),
        ),
        migrations.AddField(
            model_name='execution',
            name='test_input',
            field=models.TextField(blank=True, verbose_name='Входные данные'),
        ),
        migrations.AddField(
            model_name='execution',
            name='test_is_passed',
            field=models.BooleanField(default=False, verbose_name='Тест ройден?'),
        ),
        migrations.AddField(
            model_name='execution',
            name='test_output_correct',
            field=models.TextField(blank=True, verbose_name='Верные выходные данные'),
        ),
    ]
