# Generated by Django 2.1.2 on 2018-11-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0036_auto_20181120_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='execution_summary',
            field=models.TextField(blank=True, verbose_name='Итог запуска'),
        ),
    ]
