# Generated by Django 2.1.2 on 2018-11-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0037_auto_20181120_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='test_is_passed',
            field=models.BooleanField(default=False, verbose_name='Тест пройден?'),
        ),
    ]
