# Generated by Django 2.1.2 on 2018-11-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0038_auto_20181123_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('OK', 'Задача решена'), ('TF', 'Тест провален'), ('WA', 'Неверный ответ'), ('NA', 'Ответ отсутствует'), ('CE', 'Ошибка компиляции'), ('RE', 'Ошибка выполнения'), ('FE', 'Ошибка операций с плавающей точкой'), ('SF', 'Ошибка при работе с памятью'), ('TL', 'Превышено ограничение по времени'), ('ML', 'Превышено ограничение по памяти'), ('UN', 'Задача не проверена')], default='UN', max_length=2, verbose_name='Статус'),
        ),
    ]
