# Generated by Django 2.1.2 on 2018-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0039_auto_20181123_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='compilation_command',
            field=models.TextField(blank=True, verbose_name='Команда компиляции'),
        ),
        migrations.AddField(
            model_name='execution',
            name='execution_command',
            field=models.TextField(blank=True, verbose_name='Команда выполнения'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('OK', 'Задача решена'), ('TF', 'Тест провален'), ('WA', 'Неверный ответ'), ('NA', 'Ответ отсутствует'), ('CE', 'Ошибка компиляции'), ('RE', 'Ошибка выполнения'), ('FE', 'Ошибка операций с плавающей точкой'), ('SF', 'Ошибка при работе с памятью'), ('TL', 'Превышено ограничение по времени'), ('ML', 'Превышено ограничение по памяти'), ('UN', 'Посылка не проверена')], default='UN', max_length=2, verbose_name='Статус'),
        ),
    ]
