# Generated by Django 2.1.4 on 2019-03-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0040_auto_20181222_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Легкая'), (1, 'Средняя'), (2, 'Сложная'), (3, 'Очень сложная')], default=0, verbose_name='Сложность'),
        ),
    ]
