# Generated by Django 2.1.4 on 2019-04-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0041_auto_20190301_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='exception',
            field=models.TextField(default='', verbose_name='Исключение'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='compilation_command',
            field=models.TextField(default='', verbose_name='Команда компиляции'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='compilation_stderr',
            field=models.TextField(default='', verbose_name='Вывод компилятора в stderr'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='compilation_stdout',
            field=models.TextField(default='', verbose_name='Вывод компилятора в stdout'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='compilation_time',
            field=models.FloatField(default=0.0, verbose_name='Время компиляции'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='execution_command',
            field=models.TextField(default='', verbose_name='Команда выполнения'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='execution_memory',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано памяти'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='execution_stderr',
            field=models.TextField(default='', verbose_name='Вывод программы в stderr'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='execution_stdout',
            field=models.TextField(default='', verbose_name='Вывод программы в stdout'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='execution_summary',
            field=models.TextField(default='', verbose_name='Итог запуска'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='execution_time',
            field=models.FloatField(default=0.0, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='test_input',
            field=models.TextField(default='', verbose_name='Входные данные'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='test_output',
            field=models.TextField(default='', verbose_name='Выходные данные'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='test_output_correct',
            field=models.TextField(default='', verbose_name='Верные выходные данные'),
        ),
    ]
