# Generated by Django 2.1.4 on 2019-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0043_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.AddField(
            model_name='solution',
            name='problems',
            field=models.ManyToManyField(to='contests.Problem', verbose_name='Задача'),
        ),
    ]
