# Generated by Django 2.1.4 on 2019-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0044_auto_20190429_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='fntest',
            name='compile_args',
        ),
        migrations.RemoveField(
            model_name='fntest',
            name='compile_args_override',
        ),
        migrations.RemoveField(
            model_name='fntest',
            name='launch_args',
        ),
        migrations.RemoveField(
            model_name='fntest',
            name='launch_args_override',
        ),
        migrations.RemoveField(
            model_name='fntest',
            name='problem',
        ),
        migrations.AddField(
            model_name='fntest',
            name='pattern',
            field=models.TextField(default='', verbose_name='Шаблон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fntest',
            name='problems',
            field=models.ManyToManyField(to='contests.Problem', verbose_name='Задачи'),
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
