# Generated by Django 2.1.4 on 2019-05-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0048_auto_20190505_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('level',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='result',
        ),
    ]
