# Generated by Django 2.1.4 on 2019-08-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0049_auto_20190508_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fntest',
            name='handler',
            field=models.CharField(choices=[('fsm.init', 'fsm: тривиальный'), ('fsm.comm', 'fsm: общий'), ('fsm.spec', 'fsm: специальный'), ('lss.init', 'lss: тривиальный'), ('lss.main', 'lss: основной'), ('lss.degn', 'lss: вырожденная матрица'), ('lss.insl', 'lss: несовместная матрица'), ('lss.degm', 'lss: вырожденный минор'), ('evc.init', 'evc: тривиальный'), ('evc.main', 'evc: основной'), ('evc.extd', 'evc: расширенный')], max_length=100, verbose_name='Обработчик'),
        ),
    ]
