# Generated by Django 2.1.4 on 2019-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0050_auto_20190806_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fntest',
            name='handler',
            field=models.CharField(choices=[('fsm.init', 'файловый менеджер: тривиальный'), ('fsm.comm', 'файловый менеджер: общий'), ('fsm.spec', 'файловый менеджер: специальный'), ('mem.init', 'менеджер памяти: тривиальный'), ('mem.comm', 'менеджер памяти: общий'), ('mem.spec', 'менеджер памяти: специальный'), ('lss.init', 'линейные системы: тривиальный'), ('lss.main', 'линейные системы: основной'), ('lss.degn', 'линейные системы: вырожденная матрица'), ('lss.insl', 'линейные системы: несовместная матрица'), ('lss.degm', 'линейные системы: вырожденный минор'), ('evc.init', 'собственные значения: тривиальный'), ('evc.main', 'собственные значения: основной'), ('evc.extd', 'собственные значения: расширенный')], max_length=100, verbose_name='Обработчик'),
        ),
    ]
