# Generated by Django 2.1.4 on 2019-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0051_auto_20190813_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='task_id',
            field=models.UUIDField(null=True, verbose_name='Идентификатор асинхронной задачи'),
        ),
    ]
