# Generated by Django 2.1.4 on 2019-09-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0052_submission_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ('date_created',), 'verbose_name': 'Запуск', 'verbose_name_plural': 'Запуски'},
        ),
    ]
