# Generated by Django 2.1.4 on 2019-09-07 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0053_auto_20190901_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Assignment', verbose_name='Задание'),
        ),
    ]
