# Generated by Django 2.1.4 on 2019-09-08 11:07

from django.db import migrations


def connect_submissions_to_assignments(apps, schema_editor):
    Assignment = apps.get_model('contests', 'Assignment')
    Submission = apps.get_model('contests', 'Submission')
    for assignment in Assignment.objects.all():
        submissions = Submission.objects.filter(assignment__isnull=True, owner=assignment.user, problem=assignment.problem)
        submissions.update(assignment=assignment)


def clear_submission_assignment(apps, schema_editor):
    Submission = apps.get_model('contests', 'Submission')
    Submission.objects.all().update(assignment=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0054_submission_assignment'),
    ]

    operations = [
        migrations.RunPython(connect_submissions_to_assignments, reverse_code=clear_submission_assignment)
    ]
