# Generated by Django 2.2.5 on 2019-09-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0056_auto_20190911_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execution',
            name='owner',
        ),
    ]
