# Generated by Django 2.2.5 on 2020-01-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0060_auto_20191223_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='moss_report_url',
            field=models.URLField(null=True, verbose_name='Ссылка на отчет MOSS'),
        ),
    ]
