# Generated by Django 2.2.5 on 2020-01-27 16:37

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0062_submission_moss_to_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='moss_to_submissions',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='С посылками MOSS'),
        ),
    ]
