# Generated by Django 2.2.5 on 2020-02-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0065_auto_20200131_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='task_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Идентификатор асинхронной задачи'),
        ),
    ]
