# Generated by Django 2.2.12 on 2020-05-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0066_auto_20200227_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('OK', 'Задача решена'), ('TF', 'Тест провален'), ('TR', 'Требуется проверка'), ('WA', 'Неверный ответ'), ('NA', 'Ответ отсутствует'), ('TL', 'Превышено ограничение по времени'), ('ML', 'Превышено ограничение по памяти'), ('CL', 'Превышено ограничение по времени компиляции'), ('FE', 'Ошибка операции с плавающей точкой'), ('SF', 'Ошибка при работе с памятью'), ('RE', 'Ошибка выполнения'), ('CE', 'Ошибка компиляции'), ('UE', 'Ошибка кодировки'), ('PE', 'Ошибка комплектации'), ('EX', 'Неизвестная ошибка'), ('UN', 'Посылка не проверена')], default='UN', max_length=2, verbose_name='Статус'),
        ),
    ]
