# Generated by Django 3.0.6 on 2020-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0067_auto_20200514_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
