# Generated by Django 3.0.6 on 2020-10-11 15:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0068_auto_20201005_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
