# Generated by Django 3.0.6 on 2020-10-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0070_test_testsuite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_suite',
            new_name='testsuite',
        ),
    ]
