# Generated by Django 3.0.6 on 2020-10-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0071_auto_20201018_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='owner',
        ),
    ]
