# Generated by Django 3.0.6 on 2020-10-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0074_remove_testsubmission_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='testsuitesubmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.TestSuiteSubmission', verbose_name='Решение набора тестов'),
        ),
    ]
