# Generated by Django 3.0.6 on 2020-10-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0075_auto_20201030_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number',
        ),
    ]
