# Generated by Django 3.0.6 on 2020-11-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0079_testsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuitesubmission',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Процент правильных ответов'),
        ),
    ]
