# Generated by Django 3.0.6 on 2020-11-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0080_testsuitesubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
