# Generated by Django 3.0.6 on 2020-11-08 14:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0081_auto_20201108_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsuitesubmission',
            old_name='status',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=ckeditor.fields.RichTextField(verbose_name='Вопрос'),
        ),
    ]
