# Generated by Django 2.2.13 on 2020-11-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0082_auto_20201108_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
