# Generated by Django 2.2.13 on 2020-11-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0083_auto_20201110_2012'),
        ('contests', '0083_auto_20201113_2223'),
    ]

    operations = [
    ]
