# Generated by Django 2.2.13 on 2020-12-04 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0085_course_leaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='leaders',
            field=models.ManyToManyField(related_name='courses_leading', to=settings.AUTH_USER_MODEL, verbose_name='Ведущие преподаватели'),
        ),
    ]
