# Generated by Django 2.2.13 on 2020-12-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0086_auto_20201204_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ('number',), 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('number',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='contest',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер'),
        ),
    ]
