# Generated by Django 2.2.13 on 2020-12-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0087_auto_20201214_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ('number', 'id'), 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('number', 'id'), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
