# Generated by Django 2.2.13 on 2021-02-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0088_auto_20201214_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fntest',
            name='handler',
            field=models.CharField(choices=[('fsm.init', 'файловый менеджер: тривиальный'), ('fsm.comm', 'файловый менеджер: общий'), ('fsm.spec', 'файловый менеджер: специальный'), ('mem.init', 'менеджер памяти: тривиальный'), ('mem.comm', 'менеджер памяти: общий'), ('mem.spec', 'менеджер памяти: специальный'), ('lss.initial', 'линейные системы: тривиальный'), ('lss.main', 'линейные системы: основной'), ('lss.worst_lu', 'линейные системы: worst lu'), ('lss.worst_lu_t', 'линейные системы: worst lu t'), ('lss.large', 'линейные системы: большие размерности'), ('lss.degenerate', 'линейные системы: вырожденная матрица'), ('lss.insoluble', 'линейные системы: несовместная матрица'), ('lss.degenerate_major_minor', 'линейные системы: вырожденный минор'), ('evc.init', 'собственные значения: тривиальный'), ('evc.main', 'собственные значения: основной'), ('evc.extd', 'собственные значения: расширенный')], max_length=100, verbose_name='Обработчик'),
        ),
    ]
