# Generated by Django 2.2.13 on 2021-03-01 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0088_auto_20201214_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Развёрнутый ответ')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не проверено'), (2, 'Правильно'), (3, 'Неправильно')], default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Решение задачи',
                'verbose_name_plural': 'Решения задач',
                'ordering': ['question__number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('is_right', models.BooleanField(default=False, verbose_name='Правильный?')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ('date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('answer_type', models.PositiveSmallIntegerField(choices=[(1, 'Текст'), (2, 'Тест'), (3, 'Файл')], default=1, verbose_name='Способ ответа')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер')),
                ('text', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['number'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='testsuitesubmission',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='testsuitesubmission',
            name='testsuite',
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('date_created',), 'verbose_name': 'Набор задач', 'verbose_name_plural': 'Наборы задач'},
        ),
        migrations.AlterModelOptions(
            name='testsubmission',
            options={'ordering': ('date_created',), 'verbose_name': 'Решение набора задач', 'verbose_name_plural': 'Решения наборов задач'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='number',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.RemoveField(
            model_name='test',
            name='right_answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='testsuite',
        ),
        migrations.RemoveField(
            model_name='testsubmission',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='testsubmission',
            name='number',
        ),
        migrations.RemoveField(
            model_name='testsubmission',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testsubmission',
            name='testsuitesubmission',
        ),
        migrations.AddField(
            model_name='test',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest', verbose_name='Раздел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='owner',
            field=models.ForeignKey(default=479, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='owner',
            field=models.ForeignKey(default=479, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Процент правильных ответов'),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='test',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='contests.Test', verbose_name='Набор задач'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fntest',
            name='handler',
            field=models.CharField(choices=[('fsm.init', 'файловый менеджер: тривиальный'), ('fsm.comm', 'файловый менеджер: общий'), ('fsm.spec', 'файловый менеджер: специальный'), ('mem.init', 'менеджер памяти: тривиальный'), ('mem.comm', 'менеджер памяти: общий'), ('mem.spec', 'менеджер памяти: специальный'), ('lss.initial', 'линейные системы: тривиальный'), ('lss.main', 'линейные системы: основной'), ('lss.worst_lu', 'линейные системы: worst lu'), ('lss.worst_lu_t', 'линейные системы: worst lu t'), ('lss.large', 'линейные системы: большие размерности'), ('lss.degenerate', 'линейные системы: вырожденная матрица'), ('lss.insoluble', 'линейные системы: несовместная матрица'), ('lss.degenerate_major_minor', 'линейные системы: вырожденный минор'), ('evc.init', 'собственные значения: тривиальный'), ('evc.main', 'собственные значения: основной'), ('evc.extd', 'собственные значения: расширенный')], max_length=100, verbose_name='Обработчик'),
        ),
        migrations.DeleteModel(
            name='TestSuite',
        ),
        migrations.DeleteModel(
            name='TestSuiteSubmission',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Test', verbose_name='Набор задач'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Question', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(blank=True, to='contests.Option', verbose_name='Выбранные варианты'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Question', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='answer',
            name='test_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.TestSubmission', verbose_name='Решение набора задач'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('test_submission', 'question')},
        ),
    ]
