# Generated by Django 2.2.13 on 2020-12-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0088_auto_20201214_1717'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together={('course', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('contest', 'number')},
        ),
    ]
