# Generated by Django 2.2.13 on 2021-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0089_auto_20210301_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='excellent_percentage',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='Процент для оценки 5'),
        ),
        migrations.AddField(
            model_name='test',
            name='good_percentage',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Процент для оценки 4'),
        ),
        migrations.AddField(
            model_name='test',
            name='satisfactorily_percentage',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Процент для оценки 3'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='score',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Оценка'),
        ),
    ]
