# Generated by Django 2.2.13 on 2021-03-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0089_auto_20201214_1942'),
        ('contests', '0090_auto_20210303_2247'),
    ]

    operations = [
    ]
