# Generated by Django 2.2.13 on 2021-02-14 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0090_answer_option_task_taskcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCollectionSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Процент правильных ответов')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('taskcollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.TaskCollection', verbose_name='Набор заданий')),
            ],
            options={
                'verbose_name': 'Решение набора заданий',
                'verbose_name_plural': 'Решения наборов заданий',
                'ordering': ('date_created',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='testsubmission',
            name='testsuitesubmission',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='testsuitesubmission',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='testsuitesubmission',
            name='testsuite',
        ),
        migrations.AddField(
            model_name='task',
            name='answer_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Текст'), (2, 'Тест'), (3, 'Файл')], default=1, verbose_name='Способ ответа'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestSubmission',
        ),
        migrations.DeleteModel(
            name='TestSuite',
        ),
        migrations.DeleteModel(
            name='TestSuiteSubmission',
        ),
        migrations.AddField(
            model_name='answer',
            name='taskcollectionsolution',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contests.TaskCollectionSolution', verbose_name='Решение набора заданий'),
            preserve_default=False,
        ),
    ]
