# Generated by Django 2.2.13 on 2021-02-18 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0091_auto_20210214_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('answer_type', models.PositiveSmallIntegerField(choices=[(1, 'Текст'), (2, 'Тест'), (3, 'Файл')], default=1, verbose_name='Способ ответа')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер')),
                ('text', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('date_created',),
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='TaskCollectionSolution',
            new_name='TestSubmission',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='taskansweroption',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='taskcollectionsolution',
            new_name='test_submission',
        ),
        migrations.RenameField(
            model_name='testsubmission',
            old_name='taskcollection',
            new_name='test',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='task',
        ),
        migrations.RemoveField(
            model_name='option',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='option',
            name='task',
        ),
        migrations.RenameModel(
            old_name='TaskCollection',
            new_name='Test',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Test', verbose_name='Набор заданий'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.Question', verbose_name='Задание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.Question', verbose_name='Задание'),
            preserve_default=False,
        ),
    ]
