# Generated by Django 2.2.13 on 2021-03-20 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0091_merge_20210307_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solution',
            new_name='SubmissionPattern',
        ),
    ]
