# Generated by Django 2.2.13 on 2021-03-20 19:35
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0092_auto_20210320_2048'),
    ]

    operations = []
