# Generated by Django 2.2.13 on 2021-02-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0092_auto_20210218_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('date_created',), 'verbose_name': 'Ответ на задачу', 'verbose_name_plural': 'Ответы на задачи'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('date_created',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('date_created',), 'verbose_name': 'Набор задач', 'verbose_name_plural': 'Наборы задач'},
        ),
        migrations.AlterModelOptions(
            name='testsubmission',
            options={'ordering': ('date_created',), 'verbose_name': 'Решение набора задач', 'verbose_name_plural': 'Решения наборов задач'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Question', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='test_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.TestSubmission', verbose_name='Решение набора задач'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Question', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Test', verbose_name='Набор задач'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Test', verbose_name='Набор задач'),
        ),
    ]
