# Generated by Django 2.2.13 on 2021-03-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0093_auto_20210320_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionpattern',
            options={'ordering': ('date_created',), 'verbose_name': 'Шаблон посылки', 'verbose_name_plural': 'Шаблоны посылок'},
        ),
        migrations.AlterField(
            model_name='submissionpattern',
            name='problems',
            field=models.ManyToManyField(related_name='submission_patterns', to='contests.Problem', verbose_name='Задачи'),
        ),
    ]
