# Generated by Django 2.2.13 on 2021-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0093_auto_20210222_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='Правильный?'),
        ),
    ]
