# Generated by Django 2.2.13 on 2021-02-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0094_auto_20210225_1846'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'number')},
        ),
    ]
