# Generated by Django 2.2.13 on 2021-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0095_auto_20210225_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option',
        ),
        migrations.AddField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='contests.Option', verbose_name='Выбранный вариант'),
        ),
    ]
