# Generated by Django 2.2.13 on 2021-03-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0095_auto_20210321_1913'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
