# Generated by Django 2.2.13 on 2021-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0096_auto_20210226_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(blank=True, to='contests.Option', verbose_name='Выбранный вариант'),
        ),
    ]
