# Generated by Django 2.2.13 on 2021-03-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0096_auto_20210323_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
