# Generated by Django 2.2.13 on 2021-03-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0097_auto_20210323_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
