# Generated by Django 2.2.13 on 2021-03-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0098_auto_20210301_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(null=True, verbose_name='Правильный?'),
        ),
    ]
