# Generated by Django 2.2.13 on 2021-03-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0098_question_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_type',
            new_name='type',
        ),
    ]
