# Generated by Django 2.2.13 on 2021-03-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0099_auto_20210301_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_right',
        ),
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не проверено'), (2, 'Правильно'), (3, 'Неправильно')], default=1, verbose_name='Статус'),
        ),
    ]
