# Generated by Django 2.2.13 on 2021-03-23 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0099_auto_20210323_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
