# Generated by Django 2.2.13 on 2021-03-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0101_auto_20210324_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('level', 'id'), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
