# Generated by Django 2.2.13 on 2021-03-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0101_auto_20210301_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_prepared',
        ),
    ]
