# Generated by Django 2.2.13 on 2021-03-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0102_auto_20210324_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
