# Generated by Django 2.2.13 on 2021-03-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0104_auto_20210326_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер в разделе'),
        ),
        migrations.AlterField(
            model_name='testmembership',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер задачи в наборе'),
        ),
    ]
