# Generated by Django 2.2.13 on 2021-03-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0105_auto_20210326_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='problem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Problem'),
        ),
    ]
