# Generated by Django 2.2.13 on 2021-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0106_test_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_max',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Максимальная оценка'),
        ),
    ]
