# Generated by Django 2.2.13 on 2021-04-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0109_auto_20210402_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('date_created',), 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testmembership',
            options={'ordering': ('number',), 'verbose_name': 'Привязка задачи к тесту', 'verbose_name_plural': 'Привязки задач к тестам'},
        ),
        migrations.AlterModelOptions(
            name='testsubmission',
            options={'ordering': ('date_created',), 'verbose_name': 'Решение теста', 'verbose_name_plural': 'Решения тестов'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='test_submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.TestSubmission', verbose_name='Решение теста'),
        ),
        migrations.AlterField(
            model_name='testmembership',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер задачи в тесте'),
        ),
        migrations.AlterField(
            model_name='testmembership',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Test', verbose_name='Тест'),
        ),
    ]
