# Generated by Django 2.2.13 on 2021-04-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0112_auto_20210422_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='test',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='test',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='test',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.AlterUniqueTogether(
            name='testmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testmembership',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testmembership',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testsubmission',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='testsubmission',
            name='test',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestMembership',
        ),
        migrations.DeleteModel(
            name='TestSubmission',
        ),
    ]
