# Generated by Django 2.2.13 on 2021-04-26 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20210427_0211'),
        ('contests', '0113_auto_20210424_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Faculty', verbose_name='Факультет'),
        ),
    ]
