# Generated by Django 2.2.13 on 2021-04-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0114_course_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
    ]
