# Generated by Django 2.2.13 on 2021-04-27 14:19

from django.db import migrations


def update_courses(apps, schema_editor):
    Faculty = apps.get_model('accounts', 'Faculty')
    f = Faculty.objects.get(name="Прикладная Математика и Информатика")
    Course = apps.get_model('contests', 'Course')
    Course.objects.update(faculty=f)


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0115_auto_20210427_1705'),
        ('accounts', '0041_auto_20210427_0211'),
    ]

    operations = [
        migrations.RunPython(update_courses, migrations.RunPython.noop, elidable=True)
    ]
