# Generated by Django 2.2.13 on 2021-04-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0115_auto_20210427_1705'),
        ('accounts', '0041_auto_20210427_0211'),
    ]

    operations = []
