# Generated by Django 2.2.13 on 2021-05-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0116_auto_20210427_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Faculty', verbose_name='Факультет'),
            preserve_default=False,
        ),
    ]
