# Generated by Django 2.2.13 on 2021-06-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0118_assignment_deadline'),
        ('contests', '0118_submission_footprint'),
    ]

    operations = [
    ]
