# Generated by Django 2.2.13 on 2021-07-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0121_auto_20210713_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title_unofficial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Неофициальное название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_official',
            field=models.CharField(max_length=100, verbose_name='Официальное название'),
        ),
    ]
