# Generated by Django 2.2.13 on 2021-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0122_auto_20210713_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title_official',
            field=models.CharField(help_text='Официальное название будет использовано при составлении отчетных документов', max_length=100, verbose_name='Официальное название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_unofficial',
            field=models.CharField(blank=True, help_text='Неофициальное название будет отображено для пользователей сайта', max_length=100, null=True, verbose_name='Неофициальное название'),
        ),
    ]
