# Generated by Django 2.2.13 on 2021-08-08 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0124_auto_20210802_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='leaders',
            field=models.ManyToManyField(related_name='leading', to=settings.AUTH_USER_MODEL, verbose_name='Ведущие преподаватели'),
        ),
        migrations.CreateModel(
            name='CourseLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(choices=[(0, 'Все'), (1, '1'), (2, '2')], default=0, verbose_name='Группа')),
                ('subgroup', models.PositiveSmallIntegerField(choices=[(0, 'Все'), (1, '1'), (2, '2')], default=0, verbose_name='Подгруппа')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.Course', verbose_name='Преподаваемый курс')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель курса')),
            ],
            options={
                'verbose_name': 'Преподаватель курса',
                'verbose_name_plural': 'Преподаватели курсов',
            },
        ),
        migrations.AddConstraint(
            model_name='courseleader',
            constraint=models.UniqueConstraint(fields=('course', 'leader'), name='unique_course_leader'),
        ),
    ]
