# Generated by Django 2.2.13 on 2021-08-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0125_auto_20210808_1535'),
    ]

    operations = []
