# Generated by Django 2.2.13 on 2021-08-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0126_auto_20210811_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='leaders',
        ),
    ]
