# Generated by Django 2.2.13 on 2021-08-11 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0127_remove_course_leaders'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='leaders',
            field=models.ManyToManyField(related_name='leading', through='contests.CourseLeader', to=settings.AUTH_USER_MODEL, verbose_name='Ведущие преподаватели'),
        ),
    ]
