# Generated by Django 2.2.25 on 2022-02-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0130_auto_20211212_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('Program', 'Способ ответа: программа'), ('Text', 'Способ ответа: текст'), ('Verbal', 'Способ ответа: устно'), ('', 'Способ ответа: очно'), ('Files', 'Способ ответа: файлы'), ('Options', 'Способ ответа: варианты'), ('Test', 'Тест')], max_length=8, verbose_name='Тип'),
        ),
    ]
