# Generated by Django 2.2.25 on 2022-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0131_auto_20220203_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseleader',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Все'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='courseleader',
            name='subgroup',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Все'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('Program', 'Способ ответа: программа'), ('Text', 'Способ ответа: текст'), ('Verbal', 'Способ ответа: устно'), ('Files', 'Способ ответа: файлы'), ('Options', 'Способ ответа: варианты'), ('Test', 'Тест')], max_length=8, verbose_name='Тип'),
        ),
    ]
