# Generated by Django 2.2.25 on 2022-02-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0132_auto_20220212_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_type',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
