# Generated by Django 2.2.25 on 2022-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0133_auto_20220215_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='soft_deleted',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='course',
            name='soft_deleted',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='В корзине'),
        ),
        migrations.AddField(
            model_name='problem',
            name='soft_deleted',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='В корзине'),
        ),
        migrations.AlterUniqueTogether(
            name='contest',
            unique_together={('course', 'number', 'soft_deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('contest', 'number', 'soft_deleted')},
        ),
    ]
