# Generated by Django 2.2.25 on 2022-03-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0135_auto_20220313_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Скрытый раздел отображается только тем студентам, которым назначено хотя бы одно задание по задаче из этого раздела', verbose_name='Скрыть'),
        ),
    ]
