# Generated by Django 2.2.25 on 2022-03-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0136_contest_hidden'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subproblem',
            constraint=models.UniqueConstraint(fields=('problem', 'number'), name='unique_number_in_problem'),
        ),
    ]
