# Generated by Django 2.2.28 on 2022-07-03 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0138_auto_20220402_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('flag', models.BooleanField(default=False, verbose_name='Присутствие')),
                ('date_from', models.DateTimeField(verbose_name='Начало интервала')),
                ('date_to', models.DateTimeField(verbose_name='Конец интервала')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Course', verbose_name='Курс')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещаемость',
                'ordering': ('date_created',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'course', 'date_from', 'date_to'), name='unique_attendance'),
        ),
    ]
