# Generated by Django 2.2.28 on 2022-11-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0139_auto_20220703_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='footprint',
            field=models.TextField(),
        ),
    ]
