# Generated by Django 3.2.16 on 2023-03-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0140_auto_20221121_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 курс, I семестр'), (2, '1 курс, II семестр'), (3, '2 курс, III семестр'), (4, '2 курс, IV семестр'), (5, '3 курс, V семестр'), (6, '3 курс, VI семестр'), (7, '4 курс, VII семестр'), (8, '4 курс, VIII семестр'), (9, '1 курс, I семестр, магистратура'), (10, '1 курс, II семестр, магистратура'), (11, '2 курс, III семестр, магистратура'), (12, '2 курс, IV семестр, магистратура')], verbose_name='Уровень'),
        ),
    ]
