# Generated by Django 3.2.16 on 2023-04-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0142_auto_20230330_1552'),
    ]

    operations = []
