# Generated by Django 3.2.16 on 2023-04-08 10:49

from django.db import migrations


def fix_mathjax_inline_wrappers(apps, schema_editor):
    Course = apps.get_model('contests', 'Course')
    for course in Course.objects.filter(title_official__contains="Практикум на ЭВМ."):
        for contest in course.contest_set.all():
            opening_wrappers = contest.description.count(r"\\(")
            closing_wrappers = contest.description.count(r"\\)")
            if opening_wrappers > 0 and opening_wrappers == closing_wrappers:
                contest.description = contest.description.replace(r"\\(", r"\(")
                contest.description = contest.description.replace(r"\\)", r"\)")
                contest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0142_auto_20230330_1552'),
    ]

    operations = [
        migrations.RunPython(fix_mathjax_inline_wrappers, migrations.RunPython.noop, elidable=True)
    ]
