# Generated by Django 3.2.18 on 2023-05-21 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0143_auto_20230408_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор курса'),
        ),
        migrations.CreateModel(
            name='CourseAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор курса')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.course', verbose_name='Преподаваемый курс')),
            ],
            options={
                'verbose_name': 'Автор курса',
            },
        ),
        migrations.AddConstraint(
            model_name='courseauthor',
            constraint=models.UniqueConstraint(fields=('course', 'author'), name='unique_course_author'),
        ),
    ]
