# Generated by Django 3.2.18 on 2023-05-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0143_auto_20230408_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='submission', to='contests.problem', verbose_name='Задача'),
        ),
    ]
