# Generated by Django 3.2.18 on 2023-05-24 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0144_auto_20230521_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ManyToManyField(related_name='authored', through='contests.CourseAuthor', to=settings.AUTH_USER_MODEL, verbose_name='Текущий автор'),
        ),
    ]
