# Generated by Django 3.2.19 on 2023-05-15 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0145_alter_course_leaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='remark',
            field=models.CharField(blank=True, help_text='Для преподавателей', max_length=255, verbose_name='Пометка'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='score_is_locked',
            field=models.BooleanField(default=False, help_text='Заблокированная оценка не может быть изменена системой автоматической проверки посылок', verbose_name='Заблокировать оценку'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='score_max',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)], verbose_name='Максимальная оценка'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_testable',
            field=models.BooleanField(default=True, help_text='Разрешить системе автоматически проверять посылки и обновлять оценку задания', verbose_name='Проверять автоматически'),
        ),
    ]
