# Generated by Django 3.2.19 on 2023-05-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0146_auto_20230515_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ('-course',), 'permissions': [('report_credit', 'Генерировать ведомость')], 'verbose_name': 'Зачет', 'verbose_name_plural': 'Зачеты'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-date_created',), 'permissions': [('evaluate_submission', 'Проверять Посылку'), ('download_submission', 'Скачивать Посылку'), ('moss_submission', 'Отправлять на проверку в MOSS')], 'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
    ]
