# Generated by Django 3.2.18 on 2023-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0146_userpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=128, verbose_name='Название правила')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': 'Право пользователя на курсе', 'verbose_name_plural': 'Права пользователя на курсе'},
        ),
        migrations.AddField(
            model_name='userpermission',
            name='perms',
            field=models.ManyToManyField(to='contests.Permission', verbose_name='Правила'),
        ),
    ]
