# Generated by Django 3.2.18 on 2023-10-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0147_auto_20231005_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission_name',
            field=models.CharField(max_length=128, verbose_name='Имя правила'),
        ),
    ]
