# Generated by Django 3.2.19 on 2023-08-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0147_auto_20230531_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='secure_submission',
            field=models.BooleanField(default=False, help_text='Этот режим повысит защиту от посторонней помощи студентам во время экзамена', verbose_name='Обезопасить посылки'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='secure_submission_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
