# Generated by Django 3.2.23 on 2024-04-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0148_auto_20230818_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fntest',
            name='handler',
            field=models.CharField(choices=[('fsm.init', 'файловый менеджер: тривиальный'), ('fsm.comm', 'файловый менеджер: общий'), ('fsm.spec', 'файловый менеджер: специальный'), ('mem.init', 'менеджер памяти: тривиальный'), ('mem.comm', 'менеджер памяти: общий'), ('mem.spec', 'менеджер памяти: специальный'), ('lss.initial', 'линейные системы: тривиальный'), ('lss.main', 'линейные системы: основной'), ('lss.worst_lu', 'линейные системы: worst lu'), ('lss.worst_lu_t', 'линейные системы: worst lu t'), ('lss.large', 'линейные системы: большие размерности'), ('lss.degenerate', 'линейные системы: вырожденная матрица'), ('lss.insoluble', 'линейные системы: несовместная матрица'), ('lss.degenerate_major_minor', 'линейные системы: вырожденный минор'), ('evc.init', 'собственные значения: тривиальный'), ('evc.main', 'собственные значения: основной'), ('evc.extd', 'собственные значения: расширенный'), ('tmt.main_100', 'машина тьюринга: основной, 100 тестов'), ('tmt.main_50', 'машина тьюринга: основной, 50 тестов'), ('tmt.main_25', 'машина тьюринга: основной, 25 тестов')], max_length=100, verbose_name='Обработчик'),
        ),
    ]
