# Generated by Django 3.2.23 on 2024-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0149_alter_fntest_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C'), ('PC', 'Псевдокод')], default='C++', max_length=8, verbose_name='Язык'),
        ),
    ]
