# Generated by Django 3.2.18 on 2023-10-17 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0149_auto_20231017_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='authored', to=settings.AUTH_USER_MODEL, verbose_name='Ведущий автор курса'),
        ),
    ]
