# Generated by Django 3.2.23 on 2025-05-18 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0150_alter_problem_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date_started', models.DateField(verbose_name='Дата начала')),
                ('date_finished', models.DateField(verbose_name='Дата завершения')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.course', verbose_name='Курс')),
                ('credits', models.ManyToManyField(to='contests.Credit', verbose_name='Зачеты')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
                'ordering': ('-date_started',),
                'abstract': False,
            },
        ),
    ]
