# Generated by Django 3.2.23 on 2025-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0151_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(
                default=False,
                help_text='Разрешить просмотр курса без авторизации',
                verbose_name='Публичный доступ',
            ),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_public',
            field=models.BooleanField(
                default=False,
                help_text='Разрешить просмотр раздела без авторизации',
                verbose_name='Публичный доступ',
            ),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_public',
            field=models.BooleanField(
                default=False,
                help_text='Разрешить просмотр задачи без авторизации',
                verbose_name='Публичный доступ',
            ),
        ),
    ]
