# Generated by Django 3.2.23 on 2026-04-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0152_alter_fntest_handler'),
        ('contests', '0152_public_access'),
    ]

    operations = [
    ]
