# Generated by Django 3.2.23 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0153_merge_0152_alter_fntest_handler_0152_public_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={
                'ordering': ('level', 'id'),
                'permissions': [('make_public_course', 'Открывать публичный доступ к курсу')],
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'Разрешить просмотр курса без авторизации. При включении этого параметра без авторизации станут '
                    'доступны курс, все его разделы и задачи.'
                ),
                verbose_name='Публичный доступ',
            ),
        ),
    ]
